language: node_js

node_js:
  - 12

cache:
  yarn: true
  directories:
    - node_modules
    - packages/resources/node_modules
    - packages/posts/node_modules
    - packages/web/node_modules

git:
  depth: 1

before_install:
  - pyenv global 3.7
  - pip3 install --quiet awscli
  - aws --version
  - yarn global add serverless

jobs:
  include:

    - name: "resources"
      install:
        - cd packages/resources
        - yarn install
        - cd -
      script:
        - cd packages/resources
        - yarn test
        - cd -
      deploy:
        - provider: script
          script: >-
            cd packages/resources;
            sls -v deploy;
            cd -
          skip_cleanup: true
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^develop|feature\/.*$
        - provider: script
          script: >-
            cd packages/resources;
            sls -v -s prod deploy;
            cd -
          skip_cleanup: true
          on:
            branch: master

    - name: "posts"
      install:
        - cd packages/posts
        - yarn install
        - cd -
      script:
        - cd packages/posts
        - yarn test
        - cd -
      deploy:
        - provider: script
          script: >-
            cd packages/posts;
            sls -v deploy;
            cd -
          skip_cleanup: true
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^develop|feature\/.*$
        - provider: script
          script: >-
            cd packages/posts;
            sls -v -s prod deploy;
            cd -
          skip_cleanup: true
          on:
            branch: master

    - name: "mail"
      install:
        - cd packages/mail
        - yarn install
        - cd -
      script:
        - cd packages/mail
        - yarn test
        - cd -
      deploy:
        - provider: script
          script: >-
            cd packages/mail;
            SENDGRID_API_KEY=${DEV_SENDGRID_API_KEY} sls -v deploy;
            cd -
          skip_cleanup: true
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^develop|feature\/.*$
        - provider: script
          script: >-
            cd packages/mail;
            SENDGRID_API_KEY=${PROD_SENDGRID_API_KEY} sls -v -s prod deploy;
            cd -
          skip_cleanup: true
          on:
            branch: master

    - name: "web"
      install:
        - cd packages/web
        - yarn install --production=false
        - cd -
      script:
        - cd packages/web
        - yarn test
        - cd -
      deploy:
        - provider: script
          script: >-
            cd packages/web;
            yarn build;
            sls -v deploy;
            sls -v syncToS3;
            sls -v invalidateCloudFrontCache;
            cd -
          skip_cleanup: true
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^develop|feature\/.*$
        - provider: script
          script: >-
            cd packages/web;
            APP_ENV=prod yarn build;
            sls -v -s prod deploy;
            sls -v -s prod syncToS3;
            sls -v -s prod invalidateCloudFrontCache;
            cd -
          skip_cleanup: true
          on:
            branch: master
