language: node_js

node_js:
  - 12

cache:
  npm: true
  directories:
    - node_modules

git:
  depth: 1

install:
  - npm --production=false install

script:
  - npm test

deploy:
  - provider: script
    script: npx sls deploy; npx sls syncToS3; npx sls invalidateCloudFrontCache
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script: npx sls -s prod deploy; npx sls -s prod syncToS3; npx sls -s prod invalidateCloudFrontCache
    skip_cleanup: true
    on:
      branch: master
