language: node_js
node_js: 10
cache: yarn
script:
    - yarn eslint
    - yarn test
deploy:
    - provider: script
      script: yarn amplify-deploy
      skip_cleanup: true
      on:
        branch: develop
    - provider: script
      script: yarn now-deploy-prod
      skip_cleanup: true
      on:
        branch: master
notifications:
    email:
        recipients:
            - roger@sourcier.uk
        on_success: never
        on_failure: always
git:
    depth: 1
