language: node_js
node_js: 10
cache: yarn
script:
    - yarn eslint
    - yarn test
    - yarn build
deploy:
    - provider: script
      script: yarn now-deploy
      skip_cleanup: true
      on:
        all_branches: true
    - provider: script
      script: yarn now-deploy-prod
      skip_cleanup: true
      on:
        branch: master
after_deploy:
    - yarn now-rm
notifications:
    email:
        recipients:
            - roger@sourcier.uk
        on_success: never
        on_failure: always
git:
    depth: 1
