language: node_js

node_js:
  - 12

cache:
  npm: true
  directories:
    - node_modules

git:
  depth: 1

install:
  - npm --production=false install

script:
  - npm test

deploy:
  - provider: script
    script: npx serverless deploy; npx serverless syncToS3; npx serverless invalidateCloudFrontCache
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script: npx serverless -s prod deploy; npx serverless -s prod syncToS3; npx serverless -s prod invalidateCloudFrontCache
    skip_cleanup: true
    on:
      branch: master
