language: node_js

node_js:
  - 12

cache:
  npm: true
  directories:
    - node_modules

git:
  depth: 1

before_install:
  - pyenv global 3.7
  - pip3 install --quiet awscli
  - aws --version

install:
  - npm --production=false install

script:
  - npm test

deploy:
  - provider: script
    script: >-
      npm run build;
      npx sls -v deploy;
      npx sls -v syncToS3;
      npx sls -v invalidateCloudFrontCache
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script: >-
      npm run build;
      npx sls -v -s prod deploy;
      npx sls -v -s prod syncToS3;
      npx sls -v -s prod invalidateCloudFrontCache
    skip_cleanup: true
    on:
      branch: master
