service: musical-waffle

plugins:
  - single-page-app
  - serverless-pseudo-parameters
  - serverless-bundle
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:service}-${self:custom.stage}
  distributionPath: ./build
  postsTableName: ${self:custom.prefix}-posts

  bundle:
    linting: false

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2

  environment:
    POSTS_TABLE_NAME: ${self:custom.postsTableName}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - !GetAtt PostsTable.Arn

resources:
  - ${file(resources/parameters.yml)}
  - ${file(resources/conditions.yml)}
  - ${file(resources/spa.yml)}
  - ${file(resources/spa-redirect.yml)}
  - ${file(resources/posts-table.yml)}

package:
  individually: true

functions:
  - ${file(src/api/posts/posts.yml)}
