service: musical-waffle

plugins:
  - single-page-app
  - serverless-pseudo-parameters

custom:
  stage: ${opt:stage, self:provider.stage}
  distributionPath: ./build

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2

resources:
  - ${file(resources/parameters.yml)}
  - ${file(resources/conditions.yml)}
  - ${file(resources/spa.yml)}
  - ${file(resources/spa-redirect.yml)}
