Resources:
  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Ref IdentityPoolName
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders:
        - ClientId: !Ref CognitoUserPoolClient
          ProviderName: !GetAtt CognitoUserPool.ProviderName

  CognitoIdentityPoolRoles:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId:
        Ref: CognitoIdentityPool
      Roles:
        unauthenticated: !GetAtt CognitoUnauthenticatedRole.Arn
        authenticated: !GetAtt CognitoAuthenticatedRole.Arn

  CognitoUnauthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref CognitoIdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: unauthenticated
      Policies:
        - PolicyName: CognitoAuthorizedPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              !If
                - IsProd
                -
                  - Effect: Allow
                    Action:
                      - execute-api:Invoke
                    Resource: !Sub arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/prod/GET/*
                  - Effect: Allow
                    Action:
                      - execute-api:Invoke
                    Resource: !Sub arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:7q9qe3mkcg/dev/POST/mail
                -
                  - Effect: Allow
                    Action:
                      - execute-api:Invoke
                    Resource: !Sub arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/dev/GET/*
                  - Effect: Allow
                    Action:
                      - execute-api:Invoke
                    Resource: !Sub arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:7ikidzu3j6/dev/POST/mail

  CognitoAuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref CognitoIdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
      Policies:
        - PolicyName: CognitoAuthorizedPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - execute-api:Invoke
                Resource: !Sub arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/#{Stage}/*

Outputs:
  IdentityPoolId:
    Value:
      Ref: CognitoIdentityPool
