service: musical-waffle-resources

plugins:
  - serverless-pseudo-parameters

custom:
  prefix: ${self:service}-${self:provider.stage}
  postsTableName: ${self:custom.prefix}-posts

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2

resources:
  - ${file(parameters.yml)}
  - ${file(conditions.yml)}
  - ${file(cognito-user-pool.yml)}
  - ${file(cognito-identity-pool.yml)}
