Resources:
  ApiGatewayDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref CertificateArn
      DomainName: !Ref DomainName

  ApiGatewayMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref BasePath
      DomainName: !Ref ApiGatewayDomainName
      RestApiId: !Ref ApiGatewayRestApi

Outputs:
  ApiGatewayDistributionDomainName:
    Description: The elasticache hostname
    Value: !GetAtt [ApiGatewayDomainName, DistributionDomainName]
