Resources:
  PostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref PostsTableName
      AttributeDefinitions:
        - AttributeName: slug
          AttributeType: S
      KeySchema:
        - AttributeName: slug
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
