service: musical-waffle-mail

plugins:
  - serverless-bundle
  - serverless-offline

custom:
  prefix: ${self:service}-${self:provider.stage}

  bundle:
    linting: false

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2

  environment:
    SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}
    SENDGRID_EMAIL_TO: ${env:SENDGRID_EMAIL_TO}

resources:
  - ${file(resources/api-gateway-errors.yml)}

package:
  individually: true

functions:
  Send:
    handler: src/send.default
    events:
      - http:
          path: mail
          method: post
          cors: true
          authorizer: aws_iam
