service: musical-waffle-mail

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-domain-manager

custom:
  stage: ${self:provider.stage}
  prefix: ${self:service}-${self:provider.stage}
  domains:
    prod: api.sourcier.uk
    dev: dev-api.sourcier.uk
  customDomain:
    basePath: mail
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: "${self:custom.stage}"
    createRoute53Record: false

  bundle:
    linting: false
    packager: yarn

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2

  environment:
    SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}
    SENDGRID_EMAIL_TO: ${env:SENDGRID_EMAIL_TO}
    SENDGRID_EMAIL_FROM: ${env:SENDGRID_EMAIL_FROM}
    SENTRY_DNS: ${env:SENTRY_DNS}

resources:
  - ${file(resources/api-gateway-errors.yml)}

package:
  individually: true

functions:
  Send:
    handler: src/send.default
    events:
      - http:
          path: /
          method: post
          cors: true
          authorizer: aws_iam
